/// Flutter icons Pokedex
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Pokedex
///      fonts:
///       - asset: fonts/Pokedex.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Pokedex {
  Pokedex._();

  static const _pokedexFont = 'Pokedex';
  static const String? _pokedexPackage = null;

  static const IconData pokedexGear =
      IconData(0xe800, fontFamily: _pokedexFont, fontPackage: _pokedexPackage);
  static const IconData pokedexBell =
      IconData(0xe801, fontFamily: _pokedexFont, fontPackage: _pokedexPackage);
  static const IconData pokedexPokeball =
      IconData(0xe802, fontFamily: _pokedexFont, fontPackage: _pokedexPackage);
  static const IconData pokedexPerson =
      IconData(0xe804, fontFamily: _pokedexFont, fontPackage: _pokedexPackage);
  static const IconData pokedexHouse =
      IconData(0xe805, fontFamily: _pokedexFont, fontPackage: _pokedexPackage);
}
