name: pokedex_dvd
description: A pokedex for the better pokemon hunters.

publish_to: 'deivide_paulino' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  asp: ^1.3.0
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  flutter_custom_clippers: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/core/assets/animations/
    - lib/core/assets/images/
    - lib/core/assets/svg/
    - lib/core/assets/svg/categories/

  fonts:
    - family: Pokedex
      fonts:
        - asset: lib/core/assets/icons/pokedex/fonts/Pokedex.ttf
